blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¬ Discord chat"
    url: https://liam.sh/chat
    about: On-topic and off-topic discussions.
  - name: "ğŸ™‹â€â™‚ï¸ Additional support information"
    url: https://github.com/lrstanley/.github/blob/master/SUPPORT.md
    about: Looking for something else? Check here.
